### PR TITLE
Fix length variable

### PR DESCRIPTION
**Pull request by AlfredJKwack**
Since ( img.width \* img.height ) = (data.length / 4)
And we iterate until i = length
We want to make sure we get through more than 1/4 of the pixels

### CODE REVIEW

**Comment by briangonzalez** [comment]
@AlfredJKwack Can you explain this one a little further?

**Comment by AlfredJKwack** [comment]
Sure thing,

We agree that an image (and the data stream representation thereof) is composed of 4 values, R,G,B and A, for each pixel. When we query data.length we query all of the data for the image. For a 1x1 pixel image the data.length is thus 4. From there, we can postulate that: _img.width * img.height * 4 = data.length_. When we set the length variable on line 57 we want to make sure we capture the appropriate amount of data which is currently not the case.

When I say we want to go through more than 1/4 of the pixels, its because:

- as the below snippet illustrates, in some circumstances the assignment of the length variable is done with width x height only : 

>  var length        = ( img.width * img.height ) || data.length

- and the length variable is used in a loop as below.

> 
>               // Loop over all pixels, in BLOCKSIZE iterations.
>               var i = 0;
>               while ( i < length ) {
>                 rgb[0] = data[i];
>                 rgb[1] = data[i+1];
>                 rgb[2] = data[i+2];
>                 rgbString = rgb.join(",");
> 
>                 // SNIP
> 
>                 // Increment!
>                 i += BLOCKSIZE * 4;
>               }

**Comment by AlfredJKwack** [comment]
Hi Brian,

Did my explanation make any sense? Come to think of it I'm wondering what led you to use the logical OR on [#L57](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L57). I'm sure I'm missing something in the execution logic here.

**Comment by AlfredJKwack** [comment]
Closing as resolved with one of the commits in PR #24

**Pull request closed without merging**
