### PR TITLE
Fix issue #12 - Colours are now unique

### PR DESCRIPTION
**Pull request by AlfredJKwack**
Implements a fix to ensure colours are unique. In addition it implements ideas proposed by @buffcode in the #12 discussion such that at the end of the process we sort the variable colorCounts and return the 1..<paletteSize> items (thus dropping the dominant colour). 

The implementation of the new helper functions and return values also make it easy for others should they wish to amend the palette’s behaviour.

helper functions:
- mapPalette: changed to handle the colorCounts transformation to the desired array of objects which is then sorted in descending order.
- fitPalette: fits the colors to the desired outcome size (eg. 10) by either cutting the palette down or filling the remainder with a default value.
- frmtPobj: formats the object the way we like it with 2 properties.

### CODE REVIEW

**Comment by AlfredJKwack** [comment]
@briangonzalez Is this an appropriate PR or do you want something different?

**Comment by briangonzalez** [comment]
@AlfredJKwack This is perfect! Merging. Thanks! 🍻

**Comment by AlfredJKwack** [comment]
You're welcome @briangonzalez 
I think we can close the associated defects (#8, #12, #22) when I we get a chance.

**Comment by briangonzalez** [comment]
Also, @AlfredJKwack I've gone ahead and made you a collaborator. I am going to begin work this week on making this node-compatible and I'll alert you to any changes being made.

Thanks again!

**Comment by AlfredJKwack** [comment]
Thanks for the vote of confidence @briangonzalez ! 
Let me know what you need when you're ready.

**Pull request merged**
